from time import sleep
from machine import Pin

led1 = Pin(1, Pin.OUT)
led2 = Pin(2, Pin.OUT)
led3 = Pin(3, Pin.OUT)
led4 = Pin(4, Pin.OUT)
led5 = Pin(5, Pin.OUT)
led6 = Pin(6, Pin.OUT)
led7 = Pin(7, Pin.OUT)
led8 = Pin(8, Pin.OUT)
led9 = Pin(9, Pin.OUT)



def padrao1():
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    led6.value(1)
    led7.value(1)
    led8.value(1)
    led9.value(1)
    sleep(3)
def padrao2():
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    led6.value(1)
    led7.value(1)
    led8.value(1)
    led9.value(1)
    sleep(3)
def padrao3():
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    led6.value(1)
    led7.value(0)
    led8.value(1)
    led9.value(0)
    sleep(3)
def padrao4():
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    led6.value(0)
    led7.value(1)
    led8.value(0)
    led9.value(1)
    sleep(3)
def padrao5():
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    led6.value(1)
    led7.value(0)
    led8.value(1)
    led9.value(0)
    sleep(3)
def padrao6():
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    led6.value(1)
    led7.value(1)
    led8.value(1)
    led9.value(1)
    sleep(3)

while True:
    padrao1()
    padrao2()   
    padrao3()
    padrao4() 
    padrao5() 
    padrao6()  